### PR TITLE
added avoidance of pointings close to the zenith

### PR DESCRIPTION
**Pull request by ndrory**

### CODE REVIEW

**Comment by albireox** [comment]
Hi @ndrory,

This looks good. The main problem is that this only applies to APO. For LCO we should be avoiding the are around the South Pole. In `lvmsurveysim_defaults.yaml` I added a field (not used) about whether the telescope is equatorial or altaz. The idea would be to use that to determine whether to avoid the zenith or the pole at the latitude of the observatory.

Could you add that to the code?

**Comment by ndrory** [comment]
Jose,

I'm not sure this is true. I think the most likely outcome is that all mounts will be alt-az. But I'll add code to handle equatorial mounts.

	N.

> On Mar 14, 2019, at 11:25 PM, José Sánchez-Gallego <notifications@github.com> wrote:
> 
> Hi @ndrory,
> 
> This looks good. The main problem is that this only applies to APO. For LCO we should be avoiding the are around the South Pole. In lvmsurveysim_defaults.yaml I added a field (not used) about whether the telescope is equatorial or altaz. The idea would be to use that to determine whether to avoid the zenith or the pole at the latitude of the observatory.
> 
> Could you add that to the code?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- Niv Drory —
McDonald Observatory / Dept. of Astronomy
The University of Texas at Austin
Tel: +1 512 471 6197
http://www.as.utexas.edu/~drory

**Comment by ndrory** [comment]
Jose,

where is the new field you speak about? I see no changes to lvmsurveysim_defaults.yaml, at least not with my very limited knowledge of git.

	N.

> On Mar 15, 2019, at 6:51 AM, Niv Drory <drory@astro.as.utexas.edu> wrote:
> 
> Jose,
> 
> I'm not sure this is true. I think the most likely outcome is that all mounts will be alt-az. But I'll add code to handle equatorial mounts.
> 
> 	N.
> 
>> On Mar 14, 2019, at 11:25 PM, José Sánchez-Gallego <notifications@github.com> wrote:
>> 
>> Hi @ndrory,
>> 
>> This looks good. The main problem is that this only applies to APO. For LCO we should be avoiding the are around the South Pole. In lvmsurveysim_defaults.yaml I added a field (not used) about whether the telescope is equatorial or altaz. The idea would be to use that to determine whether to avoid the zenith or the pole at the latitude of the observatory.
>> 
>> Could you add that to the code?
>> 
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 
> -- Niv Drory —
> McDonald Observatory / Dept. of Astronomy
> The University of Texas at Austin
> Tel: +1 512 471 6197
> http://www.as.utexas.edu/~drory

-- Niv Drory —
McDonald Observatory / Dept. of Astronomy
The University of Texas at Austin
Tel: +1 512 471 6197
http://www.as.utexas.edu/~drory

**Comment by albireox** [comment]
In `lvmsurveysim_defaults.yaml` there is a field (it's not a new one, it was there but unused) called `equatorial`, e.g.:

```yaml
observing_plan:
    APO:
        start_date: 2459216
        end_date: 2461041
        equatorial: false
    LCO:
        start_date: 2459216
        end_date: 2461041
        equatorial: true
```

Actually that field should be moved to `telescope` (not sure why I added it to `observing_plan`) but then it should indicate whether the exclusion zone is around the pole or the zenith.

**Comment by albireox** [comment]
I'm going to close this since it's already implemented somewhere else.

**Pull request closed without merging**
